refs: #7901: updated apache config file names to include .conf suffix along with associated postinst and prerm files that reference them.  Also incremented deb package versions to 2.3.0.

diff --git a/dataone-cn-audit-index/DEBIAN/postinst b/dataone-cn-audit-index/DEBIAN/postinst
--- a/dataone-cn-audit-index/DEBIAN/postinst
+++ b/dataone-cn-audit-index/DEBIAN/postinst
@@ -28,7 +28,7 @@ log () {
 
 SOLR_USER=tomcat7
 
-APACHE_CONF_HOME=/etc/apache2/conf.d
+APACHE_CONF_HOME=/etc/apache2/conf-available
 JETTY_HOME=/var/lib/jetty
 
 SOLR_ROOT=/var/solr
@@ -104,16 +104,18 @@ done
 
 ### Substitute server IP and PORT numbers in config files at token locations
 ##### Configure apache mod proxy for to allow solr communication between CN nodes
-cp /usr/share/dataone-cn-audit-index/debian/modproxy_cnaudit ${APACHE_CONF_HOME}/modproxy_cnaudit
-if ! (sed -i "s/$SERVER_1_TOKEN/$SERVER_1/g" ${APACHE_CONF_HOME}/modproxy_cnaudit >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
-	log "unable to set $SERVER_1 in modproxy_cnaudit"
+cp /usr/share/dataone-cn-audit-index/debian/modproxy_cnaudit.conf ${APACHE_CONF_HOME}/modproxy_cnaudit.conf
+if ! (sed -i "s/$SERVER_1_TOKEN/$SERVER_1/g" ${APACHE_CONF_HOME}/modproxy_cnaudit.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
+	log "unable to set $SERVER_1 in modproxy_cnaudit.conf"
 fi
-if ! (sed -i "s/$SERVER_2_TOKEN/$SERVER_2/g" ${APACHE_CONF_HOME}/modproxy_cnaudit >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
-	log "unable to set $SERVER_2 in modproxy_cnaudit"
+if ! (sed -i "s/$SERVER_2_TOKEN/$SERVER_2/g" ${APACHE_CONF_HOME}/modproxy_cnaudit.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
+	log "unable to set $SERVER_2 in modproxy_cnaudit.conf"
 fi
-if ! (sed -i "s/$SERVER_3_TOKEN/$SERVER_3/g" ${APACHE_CONF_HOME}/modproxy_cnaudit >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
-	log "unable to set $SERVER_3 in modproxy_cnaudit"
+if ! (sed -i "s/$SERVER_3_TOKEN/$SERVER_3/g" ${APACHE_CONF_HOME}/modproxy_cnaudit.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
+	log "unable to set $SERVER_3 in modproxy_cnaudit.conf"
 fi
+
+a2enconf modproxy_cnaudit
 
 ##### Configure jetty's start.ini with zookeeper server configuration
 ##### and bootstrap example for cn-audit index core
diff --git a/dataone-event-index/DEBIAN/postinst b/dataone-event-index/DEBIAN/postinst
--- a/dataone-event-index/DEBIAN/postinst
+++ b/dataone-event-index/DEBIAN/postinst
@@ -65,7 +65,7 @@ if ! (/etc/init.d/zookeeper stop >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 	log "zookeeper refused to stop"
 fi
 
-# Update sorl and jetty with new config files
+# Update solr and jetty with new config files
 rsync -av /usr/share/dataone-event-index/debian/solr/ $SOLR_HOME
 rsync -av /usr/share/dataone-event-index/debian/jetty/ $JETTY_HOME
 
@@ -96,16 +96,18 @@ done
 rsync -av /usr/share/dataone-event-index/debian/apache2/ $APACHE_HOME
 
 #
-# Configure modproxy_event_index
-if ! (sed -i "s/$SERVER_1_TOKEN/$SERVER_1/g" ${APACHE_HOME/conf.d}/modproxy_event_index >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
-	log "unable to set $SERVER_1 in modproxy_event_index"
+# Configure modproxy_event_index.conf
+if ! (sed -i "s/$SERVER_1_TOKEN/$SERVER_1/g" ${APACHE_HOME/conf-available}/modproxy_event_index.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
+	log "unable to set $SERVER_1 in modproxy_event_index.conf"
 fi
-if ! (sed -i "s/$SERVER_2_TOKEN/$SERVER_2/g" ${APACHE_HOME/conf.d}/modproxy_event_index >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
-	log "unable to set $SERVER_2 in modproxy_event_index"
+if ! (sed -i "s/$SERVER_2_TOKEN/$SERVER_2/g" ${APACHE_HOME/conf-available}/modproxy_event_index.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
+	log "unable to set $SERVER_2 in modproxy_event_index.conf"
 fi
-if ! (sed -i "s/$SERVER_3_TOKEN/$SERVER_3/g" ${APACHE_HOME/conf.d}/modproxy_event_index >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
-	log "unable to set $SERVER_3 in modproxy_event_index"
+if ! (sed -i "s/$SERVER_3_TOKEN/$SERVER_3/g" ${APACHE_HOME/conf-available}/modproxy_event_index.conf >> ${D1_LOG_DIR}/${D1_LOG_FILE}  2>&1); then
+	log "unable to set $SERVER_3 in modproxy_event_index.conf"
 fi
+
+a2enconf modproxy_event_index
 
 ##### Configure jetty's start.ini with zookeeper server configuration
 #
