Change tomcat6 to tomcat7 and java 1.6 to 1.7.

diff --git a/dataone-cn-os-core/DEBIAN/postinst b/dataone-cn-os-core/DEBIAN/postinst
--- a/dataone-cn-os-core/DEBIAN/postinst
+++ b/dataone-cn-os-core/DEBIAN/postinst
@@ -79,10 +79,10 @@ declare -A DEB_QUESTION_VALUES
 declare -A DB_QUESTION_CHANGED
 # The Global Constants
 
-TOMCAT=tomcat6
-TOMCAT_USER=tomcat6
-DATAONE_USER=tomcat6
-TOMCAT_HOME=/var/lib/tomcat6
+TOMCAT=tomcat7
+TOMCAT_USER=tomcat7
+DATAONE_USER=tomcat7
+TOMCAT_HOME=/var/lib/tomcat7
 SOURCE_DIR=/usr/share/dataone-cn-os-core
 SCRIPT_DIR=${SOURCE_DIR}/debian
 APACHE_CONF_DIR=/etc/apache2
@@ -91,9 +91,9 @@ D1_CONF_DIR=/etc/dataone
 NODE_PROPS="$D1_CONF_DIR/node.properties"
 LDAP_CONF_DIR=/etc/ldap
 SITES="cn-ssl"
-JAVA_SECURITY=/usr/lib/jvm/java-6-sun/jre/lib/security/java.security
-JAVA_SECURITY_EXT_DIR=/usr/lib/jvm/java-6-sun/jre/lib/ext
-JAVA_KEYSTORE=/usr/lib/jvm/java-6-sun/jre/lib/security/cacerts
+JAVA_SECURITY=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/java.security
+JAVA_SECURITY_EXT_DIR=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext
+JAVA_KEYSTORE=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/cacerts
 LDAP_USER=openldap
 CILOGON_CERTS="cilogon-basic.pem cilogon-silver.pem cilogon-openid.pem"
 SSL_CERT_DIR=/etc/ssl/certs
@@ -144,7 +144,7 @@ function log()
 	#
     if [ ! -e ${D1_LOG_DIR} ]; then
         mkdir -p ${D1_LOG_DIR}
-        chown tomcat6:tomcat6 ${D1_LOG_DIR}
+        chown tomcat7:tomcat7 ${D1_LOG_DIR}
     fi
     now=$(date "+%Y-%m-%d %H:%M:%S %Z: ")
     echo -e "${now} postinst $@" >> ${D1_LOG_DIR}/${D1_LOG_FILE}
@@ -1080,54 +1080,54 @@ function configure_tomcat()
 	## determine if the tomcat init script has a sufficient heap size
 	## XXX   XXX   XXX   -RPW    THE MAX/INITIAL HEAP PER ENVIRONMENT SHOULD BE CONFIGURED IN THE XML FILE
 	
-	if [ -e "/etc/init.d/tomcat6" ]; then
+	if [ -e "/etc/init.d/tomcat7" ]; then
 		## XXX   XXX   XXX   -RPW   
-		## we should determine if any changes have been made to /etc/init.d/tomcat6 and make a backup copy
+		## we should determine if any changes have been made to /etc/init.d/tomcat7 and make a backup copy
 		## before proceeding with its modification
-		if ! (egrep -q 'JAVA_OPTS\=.+\-Xmx' /etc/init.d/tomcat6); then
+		if ! (egrep -q 'JAVA_OPTS\=.+\-Xmx' /etc/init.d/tomcat7); then
 			log "THERE WAS AN ERROR /etc/init.d/tomcat NO LONGER HAS -Xmx DEFINED"
 			## -Xmx is not set, that is bad, the tomcat installation must
 			## have change significantly. We must manually add it to the JAVA_OPTS LINE
 			## and then change this script to handle the exact line to add it to
 			
 		else 
-			if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:MaxPermSize' /etc/init.d/tomcat6); then
+			if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:MaxPermSize' /etc/init.d/tomcat7); then
 				## THE MAIN PROBLEM WITH THIS APPROACH CURRENTLY IS SUPPORTING THE DIFFERENT ENVIRONEMENTS
 				## developer VMs will not be able to support this amount of heap space
 				## in fact our development environment probably cannot
-				if ! (sed -i.bak --regexp-extended 's/(JAVA_OPTS\=)"([^"]+\-Xmx)[0-9]+([^"]*)"/\1"\28192\3 -Xms1024M -XX:MaxPermSize=512M"/;' /etc/init.d/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-					log "Unable to modify heap space settings in /etc/init.d/tomcat6"
+				if ! (sed -i.bak --regexp-extended 's/(JAVA_OPTS\=)"([^"]+\-Xmx)[0-9]+([^"]*)"/\1"\28192\3 -Xms1024M -XX:MaxPermSize=512M"/;' /etc/init.d/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+					log "Unable to modify heap space settings in /etc/init.d/tomcat7"
 				fi
-				if ! (rm /etc/default/tomcat6.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-					log "Unable to remove /etc/default/tomcat6.bak"
+				if ! (rm /etc/default/tomcat7.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+					log "Unable to remove /etc/default/tomcat7.bak"
 				fi
 			fi
 		fi
-		if ! (egrep -q 'ulimit.+\-Hn' /etc/init.d/tomcat6); then
-			if ! (sed -i.bak --regexp-extended 's/^(\#\!\/bin\/sh.*$)/\1\n  ulimit -Hn 16384\n  ulimit -Sn 16384\n/;' /etc/init.d/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-				log "Unable to modify ulimit in /etc/init.d/tomcat6"
+		if ! (egrep -q 'ulimit.+\-Hn' /etc/init.d/tomcat7); then
+			if ! (sed -i.bak --regexp-extended 's/^(\#\!\/bin\/sh.*$)/\1\n  ulimit -Hn 16384\n  ulimit -Sn 16384\n/;' /etc/init.d/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "Unable to modify ulimit in /etc/init.d/tomcat7"
 			fi
-			if ! (rm /etc/init.d/tomcat6.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-				log "Unable to remove /etc/init.d/tomcat6.bak"
+			if ! (rm /etc/init.d/tomcat7.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+				log "Unable to remove /etc/init.d/tomcat7.bak"
 			fi
 		fi
 	fi
 	
-	if [ -e "/etc/default/tomcat6" ]; then
-		if ! (egrep -q '^\#?JAVA_OPTS\=".\{JAVA_OPTS\}.+\-XX\:\+UseConcMarkSweepGC"' /etc/default/tomcat6); then
-			if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:\+UseParallelGC' /etc/default/tomcat6); then
-				echo "JAVA_OPTS=\"\${JAVA_OPTS} -XX:+UseParallelGC\"" >> /etc/default/tomcat6
+	if [ -e "/etc/default/tomcat7" ]; then
+		if ! (egrep -q '^\#?JAVA_OPTS\=".\{JAVA_OPTS\}.+\-XX\:\+UseConcMarkSweepGC"' /etc/default/tomcat7); then
+			if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:\+UseParallelGC' /etc/default/tomcat7); then
+				echo "JAVA_OPTS=\"\${JAVA_OPTS} -XX:+UseParallelGC\"" >> /etc/default/tomcat7
 			fi
 		else 
-			if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:\+UseParallelGC' /etc/default/tomcat6); then
+			if ! (egrep -q 'JAVA_OPTS\=.+\-XX\:\+UseParallelGC' /etc/default/tomcat7); then
 				## XXX   XXX   XXX   -RPW
 				## What happens if UseConcMarkSweepGC is not a part of JAVA_OPTS, but we still want to include
 				## UseParallelGC as our main garbage collection method
-				if ! (sed -i.bak --regexp-extended 's/^\#?JAVA_OPTS=\".\{JAVA_OPTS\}.+\-XX\:\+UseConcMarkSweepGC\"/JAVA_OPTS="\$\{JAVA_OPTS\} \-XX\:\+UseParallelGC"/;' /etc/default/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-					log "Unable to modify UseConcMarkSweepGC in /etc/init.d/tomcat6"
+				if ! (sed -i.bak --regexp-extended 's/^\#?JAVA_OPTS=\".\{JAVA_OPTS\}.+\-XX\:\+UseConcMarkSweepGC\"/JAVA_OPTS="\$\{JAVA_OPTS\} \-XX\:\+UseParallelGC"/;' /etc/default/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+					log "Unable to modify UseConcMarkSweepGC in /etc/init.d/tomcat7"
 				fi
-				if ! (rm /etc/default/tomcat6.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-					log "Unable to remove /etc/default/tomcat6.bak"
+				if ! (rm /etc/default/tomcat7.bak >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+					log "Unable to remove /etc/default/tomcat7.bak"
 				fi
 			fi
 		fi
@@ -1164,20 +1164,20 @@ function configure_tomcat()
 		fi
 	fi
 	
-	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /etc/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-		log "Unable to chown on /etc/tomcat6"
+	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /etc/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to chown on /etc/tomcat7"
 	fi
-	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /var/lib/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-		log "Unable to chown on /var/lib/tomcat6"
+	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /var/lib/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to chown on /var/lib/tomcat7"
 	fi
-	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /var/log/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-		log "Unable to chown on /var/log/tomcat6"
+	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /var/log/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to chown on /var/log/tomcat7"
 	fi
-	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /var/cache/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-		log "Unable to chown on /var/cache/tomcat6"
+	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /var/cache/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to chown on /var/cache/tomcat7"
 	fi
-	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /usr/share/tomcat6 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-		log "Unable to chown on /usr/share/tomcat6"
+	if ! (chown -R ${TOMCAT_USER}:${TOMCAT_USER} /usr/share/tomcat7 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "Unable to chown on /usr/share/tomcat7"
 	fi
 
 }
